name: Pester PowerShell test on Ubuntu
on: push

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Perform a Pester test from the PSPhoneNumber.Test.ps1 file
        shell: pwsh
        run: |
          Install-Module Pester -Force
          Import-Module Pester -Force
          Invoke-Pester "./test/PSPhoneNumber.Test.ps1" -Passthru