name: Generate Module zip
on:
  release:
    types: [published]
jobs:
  build:
    name: Prepare and Upload Release Asset
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Create ZIP archive
        run: |
          zip -X -r "build/${{ github.event.repository.name }}.zip" PSPhoneNumber
      - name: Upload to Workflow Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: PSPhoneNumber-Archive
          path: "build/${{ github.event.repository.name }}.zip"
      - name: Upload to GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.event.release.tag_name }}" "build/${{ github.event.repository.name }}.zip"
